"""Self-contained Kaggle entry point generated by package_kernel.sh."""

import base64
import io
import os
import subprocess
import tarfile
from pathlib import Path

PAYLOAD = ""
runtime = Path("/kaggle/working/biohub-cycle2")
runtime.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz") as archive:
    archive.extractall(runtime, filter="data")
environment = {**os.environ, "PYTHONPATH": str(runtime / "vendor")}
input_root = Path("/kaggle/input")
zarr_inputs = sorted(input_root.rglob("*.zarr"))
if not zarr_inputs:
    raise FileNotFoundError("no competition Zarr inputs found under /kaggle/input")
test_directory = zarr_inputs[0].parent

subprocess.run(
    [
        "bash",
        str(runtime / "exec.sh"),
        str(test_directory),
        "/kaggle/working/submission.csv",
    ],
    cwd=runtime,
    env=environment,
    check=True,
    timeout=11 * 60 * 60,
)
